version: 1.0
services:
  sourcebans:
    image: morzlee/sourcebans
    volumes:
      - sourcebans:/var/www/html/
    ports:
    - "80:80"
    - "443:443"
    environment:
      - REMOVE_SETUP_DIRS: 'false'
